# Makefile for all .c file

CC = gcc

FLAGS = -Wall

all: words telefunke

#words: words.c
#	$(CC) $(FLAGS) -o runWords words.c

telefunke: telefunke.c
	$(CC) $(FLAGS) -o telefunke telefunke.c

clean:
	rm telefunke
